spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://onedayclan.cfpkqhcnnt4x.ap-northeast-2.rds.amazonaws.com:3306/onedayclan?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: clanone
    password: clanone_db_1202!
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: oclanone23@gmail.com
    password: qrdbddmsgcqedgqf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
navercloud:
  sms:
    host: https://sens.apigw.ntruss.com
    service-url: /sms/v2/services/
    service-id: ncp:sms:kr:284882888474:ondayclan
    secret-key: tw0WnPXHv09IUcMl8OHZNRj2givvjpyUYW4t4JPn
    access-key: tbWUSIAw6cEUyVP4rHEp
    from: 01033390159
jwt:
  secret: dkw92Lei20jNde2Ej223Nd2q2Nej2Le93n1Bjfnq9Ndsla9s


---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: real